--
version: 0.2
# https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
# https://docs.aws.amazon.com/codebuild/latest/userguide/sample-docker.html
# https://docs.aws.amazon.com/codepipeline/latest/userguide/ecs-cd-pipeline.html

env:
  #shell: shell-tag
  variables:
    IMAGE_LABEL: ${IMAGE_REPO_NAME}:${IMAGE_TAG}
    REPO_URI: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
    #key: "value"
    #key: "value"
  #parameter-store:
    #key: "value"
    #key: "value"
  exported-variables:
    - IMAGE_LABEL
    - REPO_URI
    #- variable
    #- variable
  #secrets-manager:
    #key: secret-id:json-key:version-stage:version-id
  #git-credential-helper: no | yes

phases:
  pre_build:
    commands:
      - echo '============== START Pre_build ============='
      - echo 'Logging in to Amazon ECR...'
      - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} \
        | docker login --username AWS --password-stdin ${REPO_URI}
    finally:
      - echo '=============== END Pre_build =============='
  build:
    commands:
      - echo '================ START Build ==============='
      - echo 'Building image'
      - echo 'Build started on `date`'
      - echo 'Building the Docker image...'         
      - docker build --tag ${IMAGE_REPO_NAME}:${IMAGE_TAG} .
      - docker tag ${IMAGE_LABEL} ${REPO_URI}/${IMAGE_LABEL}    
    finally:
      - echo '================= END Build ================'
  post_build:
    commands:
      - echo '============== START Post_build ============='
      - echo Build completed on `date`
      - echo 'Pushing the Docker image...'
      - docker push ${REPO_URI}/${IMAGE_LABEL} 
      - echo 'Creating the image definition file'
      - printf '[{"name":"mlflow-service","imageUri":"%s"}]' ${IMAGE_LABEL} > imagedefinitions.json
    finally:
      - echo '=============== END Post_build =============='

artifacts:
  files: imagedefinitions.json