---
version: 0.2
# https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
# https://docs.aws.amazon.com/codebuild/latest/userguide/sample-docker.html
# https://docs.aws.amazon.com/codepipeline/latest/userguide/ecs-cd-pipeline.html

env:
  #shell: shell-tag
  variables:
    REPO_URI: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
    IMAGE_LABEL: ${IMAGE_REPO_NAME}:${IMAGE_TAG}
    #key: "value"
    #key: "value"
  #parameter-store:
    #key: "value"
    #key: "value"
  exported-variables:
    - REPO_URI
    - IMAGE_LABEL
    #- variable
    #- variable
  #secrets-manager:
    #key: secret-id:json-key:version-stage:version-id
  #git-credential-helper: no | yes

phases:
  pre_build:
    commands:
      - echo '============== START Pre_build ============='
      - echo 'Logging in to Amazon ECR...'
      - export URI="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
      - echo "URI=${URI}"
      - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${URI}
    finally:
      - echo '=============== END Pre_build =============='
  build:
    commands:
      - echo '================ START Build ==============='
      - echo 'Building image'
      - echo 'Build started on `date`'
      - echo 'Building the Docker image...'     
      - export URI="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
      #- export LABEL="${IMAGE_REPO_NAME}:${IMAGE_TAG}"
      #- echo "LABEL=${LABEL}"
      - docker build --tag ${IMAGE_REPO_NAME}:${IMAGE_TAG}  .
      - docker tag ${IMAGE_REPO_NAME}:${IMAGE_TAG} "${URI}/${IMAGE_REPO_NAME}:${IMAGE_TAG}"" 
    finally:
      - echo '================= END Build ================'
  post_build:
    commands:
      - echo '============== START Post_build ============='
      - echo Build completed on `date`
      - echo 'Pushing the Docker image...'
      - export URI="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
      #- export LABEL="${IMAGE_REPO_NAME}:${IMAGE_TAG}"
      - docker push ${URI}/${IMAGE_REPO_NAME}:${IMAGE_TAG}
      - echo 'Creating the image definition file'
      - printf '[{"name":"mlflow-service","imageUri":"%s"}]' ${IMAGE_REPO_NAME}:${IMAGE_TAG} > imagedefinitions.json
    finally:
      - echo '=============== END Post_build =============='

artifacts:
  files: imagedefinitions.json