version: 0.2
# https://docs.aws.amazon.com/codebuild/latest/userguide/sample-docker.html
# https://docs.aws.amazon.com/codepipeline/latest/userguide/ecs-cd-pipeline.html

phases:
  pre_build:
    commands:
      - echo '============== START Pre_build ============='
      - echo 'Logging in to Amazon ECR...'
      - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
    finally:
      - echo '=============== END Pre_build =============='
  build:
    commands:
      - echo '================ START Build ==============='
      - echo 'Building image'
      - echo 'Build started on `date`'
      - echo 'Building the Docker image...'         
      - docker build --tag ${IMAGE_REPO_NAME}:${IMAGE_TAG} .
      - docker tag ${IMAGE_REPO_NAME}:${IMAGE_TAG} ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_REPO_NAME}:${IMAGE_TAG}      
    finally:
      - echo '================= END Build ================'
  post_build:
    commands:
      - echo '============== START Post_build ============='
      - echo Build completed on `date`
      - echo 'Pushing the Docker image...'
      - docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_REPO_NAME}:${IMAGE_TAG}
      - echo 'Creating the image definition file'
      - printf '[{"name":"mlflow-service","imageUri":"%s"}]' $I{MAGE_REPO_NAME}:${IMAGE_TAG} > imagedefinitions.json
    finally:
      - echo '=============== END Post_build =============='

artifacts:
    files: imagedefinitions.json